In [1]:
d = { 101: 4,102: 7,103:2}
d

{101: 4, 102: 7, 103: 2}

In [2]:
d[101]=9

In [3]:
d.get(102)

7

In [9]:
d.update({104:80})
d

{101: 9, 103: 2, 105: 34, 104: 80}

In [6]:
del d[102]

In [10]:
d.update({105:33})
d

{101: 9, 103: 2, 105: 33, 104: 80}

d[101]=5000

In [12]:
d[101]=500
d

{101: 500, 103: 2, 105: 33, 104: 80}

In [13]:
d[104]=[1000,5000,6000]
d

{101: 500, 103: 2, 105: 33, 104: [1000, 5000, 6000]}

In [15]:
d[104]

[1000, 5000, 6000]

In [16]:
d[104][2]

6000

In [17]:
d[104][0:3]

[1000, 5000, 6000]

In [18]:
d.update({103:(30,40,50,60,70)})
d

{101: 500, 103: (30, 40, 50, 60, 70), 105: 33, 104: [1000, 5000, 6000]}

In [19]:
d[103]

(30, 40, 50, 60, 70)

In [22]:
d[104].append(5)
d

{101: 500, 103: (30, 40, 50, 60, 70), 105: 33, 104: [1000, 5000, 6000, 5]}

In [24]:
d[104].append(6)
d

{101: 500,
 103: (30, 40, 50, 60, 70),
 105: 33,
 104: [1000, 5000, 6000, 5, 6, 6]}

In [25]:
d[104].append(7)
d

{101: 500,
 103: (30, 40, 50, 60, 70),
 105: 33,
 104: [1000, 5000, 6000, 5, 6, 6, 7]}

In [32]:
d[105]={'a':{30,40,50}, 'b':(1000,5000,6000,7000,9000),'c':['K',{'L':[11,22],'M':(77,88),'N'}]}
d

SyntaxError: ':' expected after dictionary key (3414309462.py, line 1)

In [3]:
x=9
if x%2==0:
   print("even")
else:
   print("odd")

odd


In [4]:
y='234'
y

'234'

In [5]:
y.isdigit()

True

In [6]:
y.isalpha()

False

In [7]:
name='Mirza'

In [12]:
if name.isalpha()==True:
    print('Accept')
else:
    print('Name should not contain digits and symbols')

Name should not contain digits and symbols


In [13]:
bool(name.lower())

True

In [14]:
bool(6875)

True

In [15]:
x='Telengana'
x

'Telengana'

In [16]:
x='mumbai'
x

'mumbai'

In [17]:
x='Maharashtra'
x

'Maharashtra'

In [18]:
x='telengana'
x

'telengana'

In [19]:
x='kjgkhb'
x

'kjgkhb'

In [33]:
x='mumbai'
if x[0].lower() in ('s','h','m'):
   print('x')
else:
    print('y')

x


In [27]:
x[0].lower()=='m'

True

In [1]:
import numpy as np

In [2]:
numpy  array operat/ions
pandas data menipulation and analysis
matplotlib and seaborn graphical analysis
sklearn ml algorithms and tachniques
statsmodels statistical analysis
scipy statistical analysis

SyntaxError: invalid syntax (621149765.py, line 1)

In [13]:
j=[5,7,2,8,4,7]
j

[5, 7, 2, 8, 4, 7]

In [5]:
d=np.array(j)
d

array([5, 7, 2, 8, 4])

In [6]:
type(d)

numpy.ndarray

In [14]:
tuple(j)

(5, 7, 2, 8, 4, 7)

In [8]:
d.size

5

In [15]:
d.reshape(5,2)

ValueError: cannot reshape array of size 5 into shape (5,2)

In [16]:
h=d.reshape(2,3)
h

ValueError: cannot reshape array of size 5 into shape (2,3)

In [17]:
h.size

NameError: name 'h' is not defined

In [18]:
j=[5,87,23,46,62,84,80,45,77,80]
j

[5, 87, 23, 46, 62, 84, 80, 45, 77, 80]

In [ ]:
y=[]
x=[]
for i in range(len(j)):
    if i%2==0:

In [1]:
Q1=np.quantile(d,0.25)
Q2=np.quantile(d,0.50)
Q3=np.quantile(d,0.75)

NameError: name 'np' is not defined

In [3]:
r=numpy.random.rand(100)

NameError: name 'numpy' is not defined

In [4]:
a=np.random.randit(20,60,15)
a

NameError: name 'np' is not defined

In [1]:
array([24,53,48,47,52,39,35,48,31,42,30,39,45,32)]

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (347570757.py, line 1)

In [3]:
a

NameError: name 'a' is not defined

In [5]:
a=[24,53,48,47,52,39,35,48,31,42,30,39,45,32]
a

[24, 53, 48, 47, 52, 39, 35, 48, 31, 42, 30, 39, 45, 32]

In [6]:
a[-4]

30

In [8]:
import numpy as np

In [10]:
np.random.seed(94)
b=np.random.randint(45,78,(7,8))
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [11]:
b[2]

array([71, 56, 51, 58, 59, 47, 68, 77])

In [12]:
b[:,7]

array([53, 60, 77, 55, 51, 47, 61])

In [13]:
b[:,3]

array([67, 77, 58, 74, 69, 77, 69])

In [14]:
b[1,3]

77

In [15]:
b[2,1:6]

array([56, 51, 58, 59, 47])

In [16]:
b[1:6:2,1:6]

array([[59, 55, 77, 69, 69],
       [45, 52, 74, 65, 53],
       [67, 53, 77, 60, 67]])

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [12]:
k=[4,6,2,9,87,40,20,55]
k

[4, 6, 2, 9, 87, 40, 20, 55]

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [13]:
pd.series(a)

AttributeError: module 'pandas' has no attribute 'series'

a=np.random.randint(20,50(5,4))
a

In [10]:
a.ndim

AttributeError: 'list' object has no attribute 'ndim'

In [8]:
pd.DataFrame(a)

0
0   4
1   6
2   2
3   9
4  87
5  40
6  20
7  55

In [14]:
df.info()

NameError: name 'df' is not defined

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')